name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make Build
      run: make Build -C /home/runner/work/M1_Tic-Tac-Toe_Game/M1_Tic-Tac-Toe_Game/3_Implementation
  
